import Head from 'next/head'
import PostCard from '../components/PostCard';
import Mylayout from '../components/Mylayout';

export async function getServerSideProps() {
  const res = await fetch(`https://gorest.co.in/public/v2/posts`)
  const posts = await res.json()

  const getusers = Promise.all(posts.map(async item => {
    const req = await fetch(`https://gorest.co.in/public/v2/users/${item.id}`)
    const res = await req.json()
    return res;
  }))
  const users = await getusers;
  
  return {
      props: {
          posts,
          users
      }, // will be passed to the page component as props
  }
}

export default function Home({posts, users}) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Mylayout>
          <PostCard
            data={posts}
            users={users}
          />
      </Mylayout>
    </>
  )
}
